---
stages:
  - test

before_script:
  # Install tox (needed for testing)
  - pip3 install tox

# -----------------------------------------------------------------------------

test:py36:
  image: python:3.6
  stage: test
  script:
    - tox -e py36

test:py37:
  image: python:3.7
  stage: test
  script:
    - tox -e py37
